modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL = "https://github.com/infernalstudios/Infernal-Expansion-Redux/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "${mod_id}.png"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.7,5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="cloth_config"
mandatory=false
versionRange="[11.1.118,)"
ordering="NONE"
side="BOTH"